<?php
//Start plugin
$plugin = new Plugin();

//Do request
if(isset($_POST) &&! empty($_POST)) {
  //Errors and pdf link
  $errors = array();
  $pdf_links = array();

  //Parse csv
  $csv = array_map(function($v) {
    return str_getcsv($v, ($_POST["seperator"] ?? ","));
  }, file($_FILES["csv"]["tmp_name"]));
  $csv_headline = array_flip($csv[0]);


  //Check
  if( isset($csv_headline["groupID"]) && isset($csv_headline["email"]) ) {
    //Start Zip
    $autogenerated = new ZipArchive();

    if($autogenerated->open( dirname(__FILE__) . "/medias/zip/" . time() . "_" . pathinfo($_FILES["csv"]["name"], PATHINFO_FILENAME ) . ".zip", ZipArchive::CREATE) === false) {
      exit("Cannot open file");
    }
    //Generate ticket
    foreach( array_slice($csv, 1) as $key => $ticket_values ) {
      //Add time (10seconds per ticket)
      set_time_limit(10);

      //Create new ticket class
      $ticket = new Ticket();
      $group = new Group();
      $group->groupID = $ticket_values[$csv_headline["groupID"]];

      //Check if ticket send
      $send = isset($ticket_values[$csv_headline["send"]]) ? (in_array( $ticket_values[$csv_headline["send"]], array("yes", "y", "ja", "j") ))  : false;

      //Add ticket
      $add_ticket = $ticket->add(array(
        "groupID" => $ticket_values[$csv_headline["groupID"]],
        "email" => $ticket_values[$csv_headline["email"]],
        "amount" => $ticket_values[$csv_headline["amount"]] ?? $group->values()["price"],
        "payment" => $ticket_values[$csv_headline["payment"]] ?? 2,
        "custom" => $ticket_values[$csv_headline["custom"]] ?? null,
        "coupon" => $ticket_values[$csv_headline["coupon"]] ?? null,
      ), true, $send);
      array_push($errors, $add_ticket);

      //PDF
      $pdf_link = $url . "pdf/ticket/?ticketToken=" . urlencode($ticket->ticketToken);

      //Add to zip
      $autogenerated->addFromString(urlencode($ticket->ticketToken) . ".pdf", file_get_contents($pdf_link));

      //Add pdf to array
      array_push($pdf_links, $pdf_link);
    }

    //Close Zip
    $autogenerated->close();

    //Echo success
    Action::success("<strong>" . array_count_values($errors)[1] . "</strong> " . ((array_count_values($errors)[1] > 1) ? "Tickets" : "Ticket") . " wurden erfolgreich erstellt");

    //Echo errors
    foreach($errors as $error) {
      if($error == 6) {
        Actionerror::fail("Coupon konnte nicht angewendet werden.");
      }elseif($error == 5) {
        Action::fail("Die Mail konnte nicht versendet werden.");
      }elseif($error == 4) {
        Action::fail("Das Zeitfenster um ein Ticket zu lösen ist <strong>nicht</strong></b> offen. Konsultiere die Gruppe für nähere Infomrationen.");
      }elseif($error == 3) {
        Action::fail("Die maximale Anzahl an Tickets wurde erreicht.");
      }elseif($error == 2) {
        Action::fail("Die maximale Anzahl an Tickets pro Benutzer wurde erreicht.");
      }elseif($error == 0) {
        Action::fail("Das Ticket konnte nicht erstellt werden");
      }
    }
  }else {
    Action::fail("Die Indexspalte groupID order email fehlt!");
  }
}
?>

<div class="autogenerate-tickets">
  <!-- Form -->
  <form action="<?php echo $url . "?id=" . $mainPage . "&sub" . $page; ?>" method="post" enctype="multipart/form-data">
    <h1>Autogenerate Tickets</h1>
    <span>Vergewissern Sie sich, vor Gebrauch die <a href="#anleitung">Anleitung</a> zu studieren</span>
    <label class="file-input">
      <input type="file" name="csv" accept=".csv" onchange="this.nextElementSibling.innerHTML = 'You choose: <b>' + this.value.substring(this.value.lastIndexOf('\\')+1) + '</b>';" required/>
      <div class="draganddrop">Click to select file</div>
    </label>
    <label class="txt-input">
      <input type="text" name="seperator" value=",">
      <span class="placeholder">Seperator</span>
    </label>
    <button onclick="this.innerHTML = 'Diese Aktion kann einige Minuten in anspruch nehmen. Bitte schliessen Sie das Fenster nicht.'">Tickets generieren</button>
  </form>

  <!-- Autogenerated -->
  <h1 class="title">Generierte Tickets</h1>
  <table class="rows">
    <tr>
      <th>CSV Name</th>
      <th>Upload-Zeit</th>
      <th>Tickets Download</th>
    </tr>

  <?php
  //Get all zips
  $zips = glob( dirname(__FILE__) . "/medias/zip/*.zip", GLOB_NOSORT);

  //List all zips
  foreach($zips as $zip) {
    //ZIP
    $infos = explode("_", pathinfo($zip, PATHINFO_FILENAME ));

    //HTML
    echo '<tr>';
      echo '<td>' . $infos[1] . '.csv</td>';
      echo '<td>' . date("d.m.Y H:i:s", $infos[0]) . '</td>';
      echo '<td><a href="' . $url . "/plugins/" . basename(dirname(__FILE__)) . "/medias/zip/" . basename($zip) . '" title=".Zip herunterladen" style="text-decoration: none; color: black; display: flex;"><img src=" '. $url . '/plugins/' . basename(dirname(__FILE__)) . '/medias/zip.svg" />Herunterladen</a></td>';
    echo '</tr>';
  }
   ?>
  </table>

  <div class="anleitung" id="anleitung">
    <h1>Anleitung</h1>
    <p>
      Verwenden Sie ein valides CSV (<a href="https://csvlint.io/" target="_blank">Überprüfen Sie es z.B. mit csvlint.io</a>). Das CSV muss zwingend die Spalten <i>groupID</i> und <i>email</i> bestizen. Optional können noch <i>amount, payment, custom, coupon</i> und <i>send</i> hinzugefügt werden. Bitte beachten Sie, dass die Namen der jeweiligen Spalten in der ersten Zeile eingetragen werden müssen. Die Reihenfolge spielt dabei keine Rolle. Beachten Sie, dass der Trenner im Feld <i>Seperator</i> mit dem des CSV-Dokuments übereinstimmt. Wurde die Aktion einmal ausgeführt, kann Sie nicht wiederhergestellt werden!
    </p>
    <p>
      <u>Genauere beschreibung der jeweiligen Spalten:</u><br />
      <strong>groupID</strong><br />
      Geben Sie die ID (Zahl) der Gruppe an, zu welcher das Ticket gehört. Bitte beachten Sie, dass diese Gruppe bereits unter Ticket->Gruppen ersichtlich ist. Beachten Sie, dass noch genügen Tickets für diese Gruppe zur Verfügung stehen. Ansonsten wird ein Fehler ausgegeben<br />
      <strong>email</strong><br />
      Diese E-Mail wird verwendet um den Benutzer wieder zu erkennen. Beachten Sie, dass der Wert bei TPU entsprechend gesetzt wird. Ansonsten wird ein Fehler ausgegeben.<br />
      <strong>amount</strong><br />
      Wenn der Amount leer gelassen wird, wird automatisch der Preis, definiert in der Gruppe, übernommen.<br />
      <strong>payment</strong><br />
      Setzen Sie payment zu 2: Nicht bezahlt; 1: Per Rechnung bezahlt; 0: Per Onlinezahlung bezahlt. Wir das Feld leer gelassen, wird der Zahlungsstatus auf 2 (nicht bezahlt) gesetzt.<br />
      <strong>custom</strong><br />
      Hier können eigene Informationen hinzugefügt werden. Bitte beachten Sie, dass Sie ein valides JSON verwenden für die spätere visuelle Darstellung<br />
      <strong>coupon</strong><br />
      Geben Sie die ID des zu verwendenden Coupons ein. Beachten Sie, dass der Coupon unter Coupons->Alle Coupons ersichtlich ist und genügend Verwendungen noch zur Verfügung hat.<br />
      <strong>send</strong><br />
      Verwenden Sie in diesem Feld Ja (Yes, y, j) oder Nein (n, no) um mitzuteilen, ob Sie dem Kunden eine Mail mit dem Ticket zustellen möchten.<br />
    </p>
    <p>
      Um Fehler auszuschliessen, verwenden Sie am besten diese <a href="<?php echo $url; ?>/plugins/<?php echo basename(dirname(__FILE__)); ?>/medias/template.csv">Vorlage</a>. Nach erfolgreicher Generierung der Tickets, können Sie alle in einem Zip herunterladen.
    </p>
  </div>

</div>
